### ISSUE TITLE
Tab Layout과 Swiper 기능 분리 및 불필요한 로직 제거

### ISSUE THREAD

**Issue by semnil5202** [map-befine-official/map-befine-swiper#2]
## 여러 기능의 혼합으로 인한 관심사 분리 미흡
  a. Tab Layout과 Swiper 의 기능 한 컴포넌트에 존재하여, 컴포넌트 구현 복잡도가 상승. 유지보수가 어려운 문제점이 있다.
  b. 오토 플레이 버튼, 탭 박스 버튼 등 사용하지 않는 UI 로직이 잔재한다.
  c. 당연히 지원되야 하는 기능(반응형 여부, 터치 스와이핑 여부)을 props로 한 번 더 지정해줘야하는 불편함이 존재한다.

## Tasks ✅
- [x] Tab Layout을 Swiper 내부의 기능으로 정의하고 Swiper와 관련된 기능만 남겨둔다.
- [x] 불필요한 UI 로직을 제거한다.
- [x] 반응형 여부, 터치 스와이핑 등 당연히 지원되야 하는 기능은 props으로 받지 않는다.
- [x] resize 이벤트 핸들링 로직 등 각종 자잘한 버그를 개선한다.

**Comment by jiwonh423** [comment]
![image](https://github.com/map-befine-official/map-befine-swiper/assets/33995840/6c305121-04ea-46c4-a9dc-6514b737b900)
